name: "AI Sec Linter"
description: "Run the AI Sec linter for Terraform and Kubernetes configurations."
author: "Darren Rabbitt"

inputs:
  infra_dir:
    description: "Path to the infrastructure directory to lint."
    required: true
  openai_api_key:
    description: "OpenAI API key for AI Sec."
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AI Sec Linter
      shell: bash
      run: |
        mkdir -p reports
        docker run --rm \
          -e INFRA_DIR="/app/infra" \
          -e OPENAI_API_KEY="${{ inputs.openai_api_key }}" \
          -v "${{ inputs.infra_dir }}:/app/infra:ro" \
          -v "${PWD}/reports:/app/reports" \
          darrendev80/ai_sec:latest --no-dash
    - name: Upload Report as Artifact
      if: always() # Ensure this step runs even if the linter fails
      uses: actions/upload-artifact@v3
      with:
        name: ai-sec-report
        path: reports/report.json