name: "AI Sec Linter"
description: "Run the AI Sec linter for Terraform and Kubernetes configurations."
author: "Darren Rabbitt"

inputs:
  infra_dir:
    description: "Path to the infrastructure directory to lint."
    required: true
  openai_api_key:
    description: "OpenAI API key for AI Sec."
    required: true

runs:
  using: "docker"
  image: "docker://darrendev80/ai_sec:latest"
  env:
    INFRA_DIR: ${{ inputs.infra_dir }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
branding:
  icon: "shield"
  color: "blue"