name: "AI Sec Linter"
description: "Run the AI Sec linter for Terraform and Kubernetes configurations."
author: "Darren Rabbitt"

inputs:
  infra_dir:
    description: "Path to the infrastructure directory to lint."
    required: true
  openai_api_key:
    description: "OpenAI API key for AI Sec."
    required: true

runs:
  using: "docker"
  image: "docker://darrendev80/ai_sec:latest"
  env:
    INFRA_DIR: ${{ inputs.infra_dir }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
  args:
    - /bin/bash
    - -c
    - |
      # Install ngrok
      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list && \
      apt update && apt install -y ngrok

      # Start ngrok to expose port 8050
      nohup ngrok http 8050 &

      # Wait for ngrok to initialize
      sleep 5

      # Fetch the ngrok public URL
      NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
      echo "Dash server is accessible at: $NGROK_URL"

      # Run the Dash server for a limited time
      timeout 300 python3 -m ai_sec.reporting.dashboard --host 0.0.0.0 --port 8050

      echo "Dash server has stopped."
branding:
  icon: "shield"
  color: "blue"